# Generated by Django 3.1.1 on 2020-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200902_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='variant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
